services:

  db:
    container_name: db
    image: postgres
    environment:
      - POSTGRES_DB=root
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  medusa:
    container_name: medusa
    build:
      dockerfile: medusa.Dockerfile
    volumes:
      - ./z-commerce-medusa/src:/app/src
      - ./medusa.env:/app/.env
    ports:
      - 7001:7001
      - 9000:9000
    depends_on:
      - db
    command: bash -c "yarn seed && yarn dev"
#    tty: true
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/health" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  storefront:
    container_name: storefront
    build:
      dockerfile: storefront.Dockerfile
    volumes:
      - ./z-commerce-storefront/src:/app/src
      - ./storefront.env:/app/.env
    ports:
#      - 80:8000 #dev
      - 80:8001 #build
    depends_on:
      - medusa
#    command: yarn dev
    command: bash -c "yarn build && yarn start"
    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://localhost:8000" ] #dev
      test: [ "CMD", "curl", "-f", "http://localhost:8001" ] #build
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s