services:

  db:
    container_name: db
    image: postgres
    environment:
      - POSTGRES_DB=root
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]

  medusa:
    container_name: medusa
    build:
      dockerfile: medusa.Dockerfile
    volumes:
      - ./z-commerce-medusa/src:/app/src
      - ./medusa.env:/app/.env
    ports:
      - 9000:9000 # for build (admin panel is on localhost:9000/app)
    depends_on:
      db:
        condition: service_healthy
    command: bash -c "yarn seed && yarn start" # for build
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/health" ]

  storefront:
    restart: always
    container_name: storefront
    build:
      dockerfile: storefront.Dockerfile
    volumes:
      - ./z-commerce-storefront/src:/app/src
      - ./storefront.env:/app/.env
    ports:
      - 80:80 # for build & dev
    depends_on:
      medusa:
        condition: service_healthy
    command: yarn run dev # for dev
#    command: bash -c "yarn build && yarn start" # for build
#    tty: true
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost" ] # for build & dev