services:

  db:
    container_name: db
    image: postgres
    environment:
      - POSTGRES_DB=root
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]

  medusa:
    container_name: medusa
    build:
      dockerfile: medusa.Dockerfile
#    volumes:
#      - ./z-commerce-medusa/src:/app/src #dev
    env_file: medusa.env
    ports:
      - 9000:9000 # for build (admin panel is on localhost:9000/app)
    depends_on:
      db:
        condition: service_healthy
    command: bash -c "yarn seed && yarn start" # for build
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/health" ]

  storefront:
    restart: always
    container_name: storefront
    build:
      dockerfile: storefront.Dockerfile
      network: host
    #    volumes:
#      - ./z-commerce-storefront/src:/app/src #dev
    env_file: storefront.env
    ports:
      - 80:80 # for build & dev
    depends_on:
      medusa:
        condition: service_healthy
#    command: yarn run dev # for dev
    command: yarn start # for build
#    tty: true
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost" ] # for build & dev

  socket:
    restart: always
    container_name: socket
    build:
      dockerfile: socket.Dockerfile
    volumes:
      - ./z-commerce-socket/src:/app/src
#      - ./socket.env:/app/.env
    ports:
      - 8888:8888
      - 7777:7777
    depends_on:
      storefront:
        condition: service_healthy
    command: yarn run start
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888" ] # for build & dev